### ISSUE TITLE
Another project for CSV-to-YNAB conversion

### ISSUE THREAD

**Issue by torbengb** [fpoppinga/ynab-converter#1]
Hallo Finn!
I've seen that you added a YNAB repository to GitHub. Have you seen that there are already many similar projects? There is one in particular that could be very interesting for you: "bank2ynab"

https://github.com/torbengb/bank2ynab/blob/develop/README.md

If you could provide a sample CSV export (anonymized) then we could easily create the converter for your bank, too! Here's a ticket I already created for your format: https://github.com/torbengb/bank2ynab/issues/171

Let me know what you think!

Liebe Grüße aus Österreich,
Ben

**Comment by fpoppinga** [comment]
Hi Ben,

sorry for coming back to you this late, I actually didn't see this issue until now.

A big benefit of my software (admittedly this feature didn't exist at the time you created the issue) is the upload to YNAB feature. 

I also have something in the queue for downloading the transactions automatically from your bank account (which btw is ridiculous for German banks).
